# 根据当前的环境修改cuda的版本
CUDA_VER                    :=  11.4

# opencv, 不依赖`pkg-config --cflags opencv4`和`pkg-config --libs opencv4`, 系统里多个opencv版本的时候容易指错
OPENCV_HEADER               :=  /usr/local/include/opencv4
OPENCV_LIB_DIR              :=  /usr/local/lib

# TensorRT的安装目录, todo
#TENSORRT_INSTALL_DIR        :=  /home/kalfazed/packages/TensorRT-8.5.1.7

# 大家根据自己的机器的型号选择一下ARCH，这个是nvcc需要用到的参数
# 下面只是定义了ARCH一个变量, 内容为"-gencode XXX"这个string
# GeForce RTX 3070, 3080, 3090
# ARCH= -gencode arch=compute_86,code=[sm_86,compute_86]

# Kepler GeForce GTX 770, GTX 760, GT 740
# ARCH= -gencode arch=compute_30,code=sm_30

# Tesla A100 (GA100), DGX-A100, RTX 3080
# ARCH= -gencode arch=compute_80,code=[sm_80,compute_80]

# Tesla V100
# ARCH= -gencode arch=compute_70,code=[sm_70,compute_70]

# GeForce RTX 2080 Ti, RTX 2080, RTX 2070, Quadro RTX 8000, Quadro RTX 6000, Quadro RTX 5000, Tesla T4, XNOR Tensor Cores
# ARCH= -gencode arch=compute_75,code=[sm_75,compute_75]

# Jetson XAVIER
# 等价于: -gencode arch=compute_72,code=sm_72 -gencode arch=compute_72,code=compute_72
# sm_72: 生成 Jetson Xavier 实际运行用的 SASS 指令码.
# compute_72: 生成 PTX 中间码, 便于 future 兼容性(在其它 nvcc 版本上 JIT 编译).
ARCH= -gencode arch=compute_72,code=[sm_72,compute_72]

# GTX 1080, GTX 1070, GTX 1060, GTX 1050, GTX 1030, Titan Xp, Tesla P40, Tesla P4
# ARCH= -gencode arch=compute_61,code=sm_61 -gencode arch=compute_61,code=compute_61

# GP100/Tesla P100 - DGX-1
# ARCH= -gencode arch=compute_60,code=sm_60

# For Jetson TX1, Tegra X1, DRIVE CX, DRIVE PX - uncomment:
# ARCH= -gencode arch=compute_53,code=[sm_53,compute_53]

# For Jetson Tx2 or Drive-PX2 uncomment:
# ARCH= -gencode arch=compute_62,code=[sm_62,compute_62]

# For Tesla GA10x cards, RTX 3090, RTX 3080, RTX 3070, RTX A6000, RTX A40 uncomment:
# ARCH= -gencode arch=compute_86,code=[sm_86,compute_86]
